version: '3'

volumes:
    prometheus_data:
    grafana_data:

services:

  prometheus:
    user: root
    privileged: true
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    restart: unless-stopped
    ports:
      - "9090:9090"
  
  alertmanager:
    user: root
    privileged: true
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    ports:
      - "9093:9093"
  
  cadvisor:
    user: root
    privileged: true
    image: gcr.io/google-containers/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /cgroup:/sys/fs/cgroup:ro
      - /dev/disk/:/dev/disk:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    ports:
      - "8080:8080"

  grafana:
    user: root
    privileged: true
    image: grafana/grafana    
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - "3000:3000"

  webhook:
    user: root
    privileged: true
    image: adi10hero/simple-webhook-reciever
    container_name: webhook
    restart: unless-stopped
    ports:
      - "5000:5000"
  
  collectd-exporter:
    user: root
    privileged: true
    image: prom/collectd-exporter
    container_name: collectd-exporter
    ports:
      - "9103:9103"
      - "25826:25826/udp"
    command:
       - --web.listen-address=":9103"
       - --collectd.listen-address=":25826"
    restart: always
